services:
  - type: web
    name: apuestapr-registration
    runtime: python
    repo: https://github.com/apuestapr/apuestapr-registration
    branch: dk/8/kyc-shufti
    buildCommand: poetry install --no-root
    startCommand: gunicorn apuestapr_registration.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: POETRY_VERSION
        value: 1.7.1
